-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:17:10 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_memsajes
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistema_memsajes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_memsajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_memsajes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sistema_memsajes` ;

-- -----------------------------------------------------
-- Table `sistema_memsajes`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_memsajes`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion_rol` VARCHAR(75) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Establece la fecha de creacion al momento de insertar un nuevo registro
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- DIEGO MUERE -- DEBEMOS SACARLO DEL SISTEMA BORRADO FISICO DELETE FROM USUARIO
-- CON DELETE EL DATO DEJA DE EXISTIR NO SE PUEDE RECUPERAR
-- EN CAMBIO CON BORRADO LOGICO (campo de deleted activo)
-- PODEMOS OCULTAR EL USUARIO PARA QUE EL CLIENTE NO LO VEA 
-- PERO NO SALE DEL SISTEMA.



-- -----------------------------------------------------
-- Table `sistema_memsajes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_memsajes`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `rol_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  INDEX `rol_id_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`rol_id`)
    REFERENCES `sistema_memsajes`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_memsajes`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_memsajes`.`mensajes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_sent_id` INT NOT NULL,
  `user_recibe_id` INT NOT NULL,
  `mensaje` TEXT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `usuario_envia_id` (`user_sent_id` ASC) VISIBLE,
  INDEX `usuario_recibe_id` (`user_recibe_id` ASC) VISIBLE,
  CONSTRAINT `mensajes_ibfk_1`
    FOREIGN KEY (`user_sent_id`)
    REFERENCES `sistema_memsajes`.`usuarios` (`id_usuario`),
  CONSTRAINT `mensajes_ibfk_2`
    FOREIGN KEY (`user_recibe_id`)
    REFERENCES `sistema_memsajes`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_memsajes`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_memsajes`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `mensaje_id` INT NULL DEFAULT NULL,
  `usuario_id` INT NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_comentario`),
  INDEX `mensaje_id` (`mensaje_id` ASC) VISIBLE,
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `comentarios_ibfk_1`
    FOREIGN KEY (`mensaje_id`)
    REFERENCES `sistema_memsajes`.`mensajes` (`id`),
  CONSTRAINT `comentarios_ibfk_2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sistema_memsajes`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Datos de prueba
-- -----------------------------------------------------
INSERT INTO `sistema_memsajes`.`roles` (`id_rol`, `nombre`, `descripcion_rol`) VALUES
  (1, 'Administrador', 'Acceso completo al sistema'),
  (2, 'Docente', 'Gestiona cursos y mensajes'),
  (3, 'Estudiante', 'Accede a mensajes y comentarios'),
  (4, 'Invitado', 'Acceso limitado de lectura'),
  (5, 'Soporte', 'Ayuda a usuarios del sistema');




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
