CREATE SCHEMA IF NOT EXISTS `esquema_tacos`
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE `esquema_tacos`;

CREATE TABLE IF NOT EXISTS `tacos` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tortilla` VARCHAR(45) NOT NULL,
    `guiso` VARCHAR(45) NOT NULL,
    `salsa` VARCHAR(45) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

